export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const PURCHASE_BURGER = 'PURCHASE_BURGER';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';

export const CREATE_DOCUMENT_START = 'CREATE_DOCUMENT_START';
export const CREATE_DOCUMENT_FAIL = 'CREATE_DOCUMENT_FAIL';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';

export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS';
export const FETCH_DOCUMENTS_DONE = 'FETCH_DOCUMENTS_DONE'

export const INIT_DOCUMENTS = 'INIT_DOCUMENTS';
export const FETCH_DOCUMENTS_START = 'FETCH_DOCUMENTS_START';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAIL = 'FETCH_DOCUMENTS_FAIL';


export const SIGN_DOCUMENT = 'SIGN_DOCUMENT';
export const SIGN_DOCUMENT_SUCCESS = 'SIGN_DOCUMENT_SUCCESS';
export const SIGN_DOCUMENT_FAIL = 'SIGN_DOCUMENT_FAIL';


export const FETCH_LINKED_DIDS = 'FETCH_LINKED_DIDS';

export const FETCH_LINKED_DIDS_START = 'FETCH_LINKED_DIDS_START';
export const FETCH_LINKED_DIDS_SUCCESS = 'FETCH_LINKED_DIDS_SUCCESS';
export const FETCH_LINKED_DIDS_FAIL = 'FETCH_LINKED_DIDS_FAIL';
export const FETCH_LINKED_DIDS_DONE = 'FETCH_LINKED_DIDS_DONE';

export const LINK_DID = 'LINK_DID';
export const INIT_DIDS = 'INIT_DIDS'
export const LINK_DID_START = 'LINK_DID_START';
export const LINK_DID_SUCCESS = 'LINK_DID_SUCCESS';
export const LINK_DID_FAIL = 'LINK_DID_FAIL';



export const FETCH_WELCOME_DATA = 'FETCH_WELCOME_DATA';

export const FETCH_WELCOME_DATA_START = 'FETCH_WELCOME_DATA_START'
export const FETCH_WELCOME_DATA_SUCCESS = 'FETCH_WELCOME_DATA_SUCCESS'
export const FETCH_WELCOME_DATA_FAIL = 'FETCH_WELCOME_DATA_FAIL'